version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    ports:
      - "27017:27017"  
  client_netflix: 
    build: ../client
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ../client:/usr/app
    restart: on-failure

  api_netflix: 
    build: api
    command: npm start
    ports:
      - "8800:8800"
    volumes:
      - ../api/:/user/app
    restart: on-failure

  admin_netflix: 
    build: admin
    command: npm start
    ports:
      - 4000:4000
    volumes:
      - ../admin/:/user/app
      
networks:
  mongo-compose-network:
    driver: bridge